# Generated by Django 2.2.12 on 2020-05-18 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsEquipment', '0005_auto_20200518_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='eqpQuantityTaken',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]))]),
        ),
    ]
