# Generated by Django 2.1.5 on 2020-05-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsEquipment', '0008_ground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ground',
            name='id',
        ),
        migrations.AddField(
            model_name='ground',
            name='gId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
