# Generated by Django 2.1.5 on 2020-05-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsEquipment', '0009_auto_20200521_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground',
            name='gId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
