# Generated by Django 2.1.5 on 2020-05-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsEquipment', '0010_auto_20200521_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='addGround',
            fields=[
                ('gId', models.AutoField(primary_key=True, serialize=False)),
                ('gname', models.CharField(max_length=50)),
            ],
        ),
    ]
