# Generated by Django 2.2.12 on 2020-05-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_userprofileinfo_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_verified',
            field=models.IntegerField(default=0),
        ),
    ]
